# -*- coding: utf-8 -*-
"""get_1_from_1000.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A3CUBlWntC8iwaEZCySrvKEsd7oKRmkQ
"""

import pandas as pd
import re
import csv
import json

print('start')

filtered_list = []
df = pd.read_csv("Part4_Result.csv")
df = df.sample(frac=0.1,replace=False)
df.to_csv("Part4_Result_1000v.csv")
print('end')
