# -*- coding: utf-8 -*-
"""getContRegularEx.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dS33JgBWuszT3odGps1K8l3FYF5Z3yde
"""

import pandas as pd
import re
import csv
import json
#f=open("gettweetbyId_log.txt", "r")
#row = f.read()
print('start')
id_list = []
event_list = []
with open('cred_event_SearchTweets.data') as myfile:
	for line in myfile:
		cur_id_list = []
		cur_event = (re.search('	(.*)	',line))
		cur_event = re.split('	', cur_event.group(1))
		print(cur_event[0])
		cur_id_list = re.findall(r'(?<=ID=)\d+',line)
		#append the event rapidly
		#print(cur_id_list)
		for i in range(len(cur_id_list)):
			event_list.append(cur_event[0])
		id_list.extend(cur_id_list)
		
		
#id_lsit = re.findall('(?<=in_reply_to_user_id_str=)(.*),', row)
myfile.close()
print(id_list[0:10])
print(event_list[0:10])
print(len(id_list))
print(len(event_list))

with open('part4_data/id_event.csv', 'a') as csvfile:
	linewriter = csv.writer(csvfile, delimiter=',', quotechar="\"")
	for i in range(len(id_list)):
		print(i)
		linewriter.writerow([id_list[i],event_list[i]])
csvfile.close()
#df = pd.DataFrame(id_list,event_list) 
#df.columns=['id','event']
#df.to_csv('idNevent.csv',index=False)
print('end')

